# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{capsh}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kyle Maxwell"]
  s.date = %q{2011-01-04}
  s.default_executable = %q{capsh}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{kmaxwell@twitter.com}
  s.executables = ["capsh"]
  s.files = [
    ".document",
     ".gitignore",
     "Rakefile",
     "VERSION",
     "bin/capsh"
  ]
  s.homepage = %q{http://github.com/fizx/capsh}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{TODO: one-line summary of your gem}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, ["= 2.5.19"])
    else
      s.add_dependency(%q<capistrano>, ["= 2.5.19"])
    end
  else
    s.add_dependency(%q<capistrano>, ["= 2.5.19"])
  end
end

